---
title: "Shyam Thomas resume"
author: Shyam Thomas
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---

Aside
================================================================================


Contact Info / Social Media {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-phone"></i> +1 763-760-2260
- <i class="fa fa-building-o"></i> Dept. of Fisheries, Wildlife & Conservation Biology, 2003 Upper Bufford Circle, St. Paul, MN, USA
- <i class="fa fa-envelope"></i> thomas.shyam@gmail.com
- <i class="fa fa-linkedin"></i> [Linkedin](https://www.linkedin.com/in/shyamthomas/)
- <i class="fa fa-github"></i> [Github](https://github.com/shyamthomas)
- <i class="fa fa-graduation-cap"></i> [Scholar](https://scholar.google.com/citations?user=wW8ZQ34AAAAJ&hl=en)
- <i class="fa fa-home"></i> [Personal](https://shyamthomas.mystrikingly.com/)


Key Skills {#skills}
--------------------------------------------------------------------------------

- R
- GIS
- MS Office
- Git / Github
- Academic writing
- Leadership & teamwork
- Creative problem solving


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made entirely in R

Last updated on `r Sys.Date()`



Main
================================================================================

SHYAM MATHEW THOMAS {#title}
--------------------------------------------------------------------------------


*Accomplished researcher with Ph.D. in ecology and 8 years of experience in leading and managing data-heavy projects | Experienced in working with a diverse range of clients within the environmental sector, and providing data analytic support and deliverables | Proficient in R programming, Arc GIS, and using version control tool such as Git | Raised more than $100K in grant money and published 12 peer-reviewed research articles in international journals*

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### St. Xaviers College

B.S. in Botany & Zoology

Mumbai, MH, India

1999


### Oklahoma State University

M.S. in Ecology

Stillwater, OK, USA

2006

### Iowa State University

Ph.D. in Ecology & Evolutionary Biology

Ames, IA, USA

2013


Professional Experience {data-icon=suitcase data-concise=TRUE}
--------------------------------------------------------------------------------

### Postdoctoral researcher

University of Minnesota

St. Paul, MN, USA

Nov 2019 - Present

- Wrangled, visualized, and managed large datasets ( 2-5 GB) using R Tidyverse & data.table packages, and ensured team members have  access to clean and complete data 
- Used general additive models and random forest algorithms within a parallel computing framework that reduced computation time  by 50%
- Incorporated spatial simulations and point pattern analyses in developing spatially-explicit predictive models
- Created R Markdown reports to ensure reproducibility and transparency of data analysis workflows for clients and collaborators
- Effectively used Git & GitHub to keep team members and clients informed of coding updates and changes


### Postdoctoral researcher

Toronto Metropoliton University

Toronto,ON, Canada

Jul 2016 - Sep 2019

- Excelled in the use of R Tidyverse package & MS Access by taking the lead
in managing and manipulating a large contaminant monitoring databases with >100,00 records
- Developed piecewise structural equation models to untangle the direct and indirect effects of climate and land-use on fish mercury levels
- Combined  Bayesian mixed-effects models and geostatistical kriging in R to develop accurate predictive models & maps of fish mercury levels
- Successfully designed & developed a prototype data visualization dashboard for a local client using R Shiny & Leaflet packages

### Postdoctoral researcher

University of California - Riverside

Riverside, CA, USA

Feb 2014 - Jun 2016

- Cleaned, integrated, and analyzed multiple monitoring datasets containing ~80,000 trap detection records spanning 6 years and 10      counties in R Studio
- Successfully coordinated with USDA in spatial data analysis, and provided the results and insights needed to develop proactive
  management approaches
- Developed predictive models and risk maps of insect pest outbreaks using
  auto-logistic regression models
- Integrated landscape pattern analysis and survival analysis to quantify the
  urban-agricultural spillover of an invasive insect pest

Grants & Awards {data-icon=star}
--------------------------------------------------------------------------------
### Diversity (Virtual) Travel Award ~ US$225

International Association of Landscape Ecology - North Americas, Annual (Virtual) Conference

Reno, NV, USA

2021

### Highly Qualified Personnel Leadership Award ~ C$ 15,000

India-Canada Centre for Innovative Multidisciplinary Partnerships to Accelerate Community Transformation and Sustainability

Vancouver, BC, Canada

2019

### Best in Science Grant ~ C$ 99,600

Ontario Ministry of Environment & Climate Change (MOECC)

Ontario, Canda

2017

### DNR Short-term research grant ~ US$ 3,039

Minnesota Department of Natural Resources

St. Paul, MN, USA

2011


Quantitative Courses / Workshops {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Statistics for Experimenters I & II

Oklahoma State University

Stillwater, OK,  USA

2003 - 2004

### Multivariate Methods for Ecology

Oklahoma State University

Stillwater, OK,  USA

2005

### Matrices & Linear Algebra

Iowa State University

Ames, IA, USA

2007

### Statistics for Spatial Data

Iowa State University

Ames, IA, USA

2008

### GIS for Natural Resource Management

Iowa State University

Ames, IA, USA

2008

### Agent-based Modeling in Ecology

Dresden University of Technology

Dresden, Germany

2009

### Intensive Course in Path Analyses & Structural Equation Modeling

University of Sherbrooke

Sherbrooke, Canada

2018



